### ISSUE TITLE
NuGet only targets DNX

### ISSUE THREAD

**Issue by adamhathcock** [serilog/serilog-framework-logging#16] opened 2015-10-07 12:33 UTC
I'm using Logging along side .NET 4.5 projects as well as DNX ones.  The Microsoft.Framework packages also allow for non-DNX usage (if it makes sense).  So Logging and Configuration do.

Would it be too much trouble to add this?

I've tried to make my own project.jsons target DNX and .NET.  However, the nupkgs they produce don't work for .NET for some reason because of some dependency issues.  I have no idea why as mine look about the same as the nupkg from the ASP.NET team.  Maybe you'll have better luck :)

**Comment by hhog-pkamburov** [comment] 2015-10-20 18:12
It should be pretty straightforward to support .NET 4.5 projects. You only need 2 lines:
project.json -> add to "frameworks":
`"net45": {
      "frameworkAssemblies": {
        "System.Runtime": ""
      }
    },`

SerilogLoggerProvider.cs -> replace:
`#if DNX451` with `#if NET45 || DNX451`

**Comment by nblumhardt** [comment] 2016-01-11 21:23
This is a dupe of #11

**Closed by nblumhardt** 2016-01-11 21:23 UTC
